### ISSUE TITLE
A native exception occurred during launch (args as a string is not supported on unix.).

### ISSUE THREAD

**Issue by yunsii** [rxliuli/tsx-vscode#1]
我是使用 WSL 作为开发环境，单次调用是没问题，保存时调用发生了如下错误：
![image](https://user-images.githubusercontent.com/18096089/219593155-116bc43a-7299-4265-b806-40a5315a97fe.png)

大佬看看能抢救下吗？

**Comment by rxliuli** [comment]
奇怪，确认 mac 上也会有这个问题，吾辈会尽快查看一下

**Comment by rxliuli** [comment]
请更新到 0.2.3 以修复该问题
